{
 "title": "API Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API GET LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "quantile(0.5, http_server_requests_seconds_sum{method=\"GET\"})"
    },
    {
     "expr": "quantile(0.95, http_server_requests_seconds_sum{method=\"GET\"})"
    },
    {
     "expr": "quantile(0.99, http_server_requests_seconds_sum{method=\"GET\"})"
    },
    {
     "expr": "quantile(1, http_server_requests_seconds_sum{method=\"GET\"})"
    }
   ]
  },
  {
   "title": "API POST LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "quantile(0.5, http_server_requests_seconds_sum{method=\"POST\"})"
    },
    {
     "expr": "quantile(0.95, http_server_requests_seconds_sum{method=\"POST\"})"
    },
    {
     "expr": "http_server_requests_seconds_sum{method=\"POST\"}"
    },
    {
     "expr": "quantile(1, http_server_requests_seconds_sum{method=\"POST\"})"
    }
   ]
  },
  {
   "title": "API PUT LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "quantile(0.5, http_server_requests_seconds_sum{method=\"PUT\"})"
    },
    {
     "expr": "quantile(0.95, http_server_requests_seconds_sum{method=\"PUT\"})"
    },
    {
     "expr": "quantile(0.99, http_server_requests_seconds_sum{method=\"PUT\"})"
    },
    {
     "expr": "quantile(1, http_server_requests_seconds_sum{method=\"PUT\"})"
    }
   ]
  },
  {
   "title": "API GET RPS 5 minutes range",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{method=\"GET\"}[5m])"
    }
   ]
  },
  {
   "title": "API POST RPS 5 minutes range",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{method=\"POST\"}[5m])"
    }
   ]
  },
  {
   "title": "API PUT RPS 5 minutes range",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{method=\"PUT\"}[5m])"
    }
   ]
  },
  {
   "title": "API GET ERROR RATE 5 minutes range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{method=\"GET\", status!=\"200\"}[5m])"
    }
   ]
  },
  {
   "title": "API POST ERROR RATE 5 minutes range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{method=\"POST\", status!=\"200\"}[5m])"
    }
   ]
  },
  {
   "title": "API PUT ERROR RATE 5 minutes range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{method=\"PUT\", status!=\"200\"}[5m])"
    }
   ]
  },
  {
   "title": "CRUD APP LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "quantile(0.5, http_server_requests_seconds_sum{service=\"crud-app-service\"})"
    },
    {
     "expr": "quantile(0.95, http_server_requests_seconds_sum{service=\"crud-app-service\"})"
    },
    {
     "expr": "quantile(0.99, http_server_requests_seconds_sum{service=\"crud-app-service\"})"
    },
    {
     "expr": "quantile(1, http_server_requests_seconds_sum{service=\"crud-app-service\"})"
    }
   ]
  },
  {
   "title": "CRUD APP RPS 5 minutes rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{service=\"crud-app-service\"}[5m])"
    }
   ]
  },
  {
   "title": "CRUD APP ERROR RATE 5 minutes rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{service=\"crud-app-service\", status!=\"200\"}[5m])"
    }
   ]
  }
 ]
}