apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090
      - job_name: latency
        metrics_path: /metrics
        static_configs:
          - targets:
              - localhost:9090
        relabel_configs:
          - source_labels: [ __address__ ]
            target_label: instance
      - job_name: rps
        metrics_path: /metrics
        static_configs:
          - targets:
              - localhost:9090
        relabel_configs:
          - source_labels: [ __address__ ]
            target_label: instance
      - job_name: error_rate
        metrics_path: /metrics
        static_configs:
          - targets:
              - localhost:9090
        relabel_configs:
          - source_labels: [ __address__ ]
            target_label: instance